apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: attacker-demo-1
spec: {}
status: {}

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pcc-demo
  name: pcc-demo
  namespace: attacker-demo-1
spec:
  containers:
  - image: chrisley75/pcc-demo:0.0.1
    imagePullPolicy: Always
    name: pcc-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
